# name = "steves-worker"
# name = "plus-production"
name = "plus-uat"
type = "webpack"

account_id = "485b87a92ea920b6afce6c8944e31633"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-04"
webpack_config = "webpack.config.js"